name: Security Scan
on:
  push:
    branches: [ 'master' ]
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at midnight

jobs:
  dependency-submission:
    name: GitHub Dependency Graph
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Submit Dependency Graph
        uses: advanced-security/maven-dependency-submission-action@v4
        with:
          directory: '.'
